### ISSUE TITLE
Error for arguments with the first example

### ISSUE THREAD

**Issue by TravelTrader** [addisonlynch/iexfinance#131]
With Python 3.6.7 I wrote that easy first code
```
from datetime import datetime
from iexfinance.stocks import Stock
from iexfinance.stocks import get_historical_intraday, get_historical_data

API_KEY = 'XXXXXX'

start = datetime(2018, 1, 1)
end = datetime(2019, 1, 1)
df = get_historical_data("TSLA", start, end, output_format='pandas')

print(len(df))
print(df.tail())
```
I think it's clear what the expected output should be. But here's my error message:
```
Traceback (most recent call last):
  File "iex.py", line 15, in <module>
    df = get_historical_data("TSLA", start, end, output_format='pandas')
  File "/home/xxx/.local/lib/python3.6/site-packages/iexfinance/stocks/__init__.py", line 39, in get_historical_data
    return HistoricalReader(symbols, start=start, end=end, **kwargs).fetch()
  File "/home/xxx/.local/lib/python3.6/site-packages/iexfinance/base.py", line 189, in fetch
    data = self._execute_iex_query(url)
  File "/home/xxx/.local/lib/python3.6/site-packages/iexfinance/base.py", line 141, in _execute_iex_query
    response = self.session.get(url=url, params=params)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/xxx/.local/lib/python3.6/site-packages/requests/adapters.py", line 315, in get_connection
    conn = self.poolmanager.connection_from_url(url)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 281, in connection_from_url
    pool_kwargs=pool_kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 229, in connection_from_host
    return self.connection_from_context(request_context)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 242, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 263, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/poolmanager.py", line 197, in _new_pool
    return pool_cls(host, port, **request_context)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 768, in __init__
    **conn_kw)
  File "/home/xxx/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 178, in __init__
    self.pool = self.QueueCls(maxsize)
TypeError: __init__() takes 1 positional argument but 2 were given
```
Anyone suggestions what is wrong? I think anything within my system, am I right? Or is it an error from the library?

Thank you!

**Comment by addisonlynch** [comment]
What ``iexfinance`` version are you using? The above code works for me in both 0.4.0 and the latest development version from git.

**Comment by TravelTrader** [comment]
It's version 0.4.0 (output of `iexfinance.__version__`).
Since I was pretty sure I did not have any bug in the code, I also opened the issue here. Where could be the reason for this mistake? Otherwise I have no problems with Python.

**Comment by TravelTrader** [comment]
I tried several function of the module and now I have the exact code like above and it works. Curious.
