### ISSUE TITLE
get_price() results in error: version 0.4.2

### ISSUE THREAD

**Issue by john8988** [addisonlynch/iexfinance#159]
## Summary (include Python version)
Python 3.7.2

I was having the 'client side error' issue for get_historical_data when using 0.4.1 version. For 0.4.1 version, I had NO issue for get_price() call.  I updated to 0.4.2 today (6/20/2019) and now I'm getting the error: 

iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.

the stack dump: 

    b=a.get_price()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stocks\base.py", line 756, in get_price
    return self._get_endpoint("price", fmt_p=fmt_p)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stocks\base.py", line 103, in _get_endpoint
    data = self.fetch(fmt_j=fmt_j, fmt_p=no_pandas)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.

**Comment by addisonlynch** [comment]
Can you post a full code snippet? The following works for me:

```python
from iexfinance.stocks import Stock

a = Stock("AAPL")
a.get_price()
```

**Comment by john8988** [comment]
Here is the snippet of the code. It's on windows

from iexfinance.stocks import Stock
import os

os.environ["IEX_TOKEN"]="******"
a = Stock("AAPL")
b=a.get_price()
print(b)

Again getting the following:

Traceback (most recent call last):
  File "C:\Users\Administrator\trade\test.py", line 6, in <module>
    b=a.get_price()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stocks\base.py", line 756, in get_price
    return self._get_endpoint("price", fmt_p=fmt_p)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stocks\base.py", line 103, in _get_endpoint
    data = self.fetch(fmt_j=fmt_j, fmt_p=no_pandas)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.

**Comment by addisonlynch** [comment]
What ``IEX_API_VERSION`` are you using?

**Comment by john8988** [comment]
Didn't set. Not sure what version.

**Comment by john8988** [comment]
Hi, I found out the problem: it was due to exceeding the free quota (500k message/mo). After I changed to another account, it worked. 

It still puzzles me that I probably made a couple of hundreds of calls on get_price and get_historical_price and now it said exceeding the quota. I guess each price row (per day) in historical price counts as one message?

Thanks anyway for spending time on this.

**Comment by sl00k** [comment]
when i use get_historical_data.close for one day its way more than 1message. its weierd

**Comment by john8988** [comment]
Just found out from API data weighting document: 

Data Weighting

Adjusted + Unadjusted
10 per symbol per time interval returned (Excluding 1d)
Example: If you query for AAPL 5 day, it will return 5 days of prices for AAPL for a total of 50.

Adjusted close only
2 per symbol per time interval returned (Excluding 1d)
use chartCloseOnly param

So 10x how many days you are getting!!!

**Comment by sl00k** [comment]
wow what a bad joke is that.
but i think i will keep it for now. i have to look for others anyway. need europe market :D
