### ISSUE TITLE
IEXQueryError

### ISSUE THREAD

**Issue by cytham** [addisonlynch/iexfinance#174]
## Summary (include Python version)
Python 3.7

from iexfinance.stocks import get_historical_data
import datetime
from dateutil.relativedelta import relativedelta

start = datetime.datetime.today() - relativedelta(years=5)
end = datetime.datetime.today()

df = get_historical_data("GE", start=start, end=end, output_format="pandas", token="my_token")

### Date/time of issue
12/9/2019 1300 GMT+8

### Expected behavior
data loaded into df

### Actual behavior
Traceback (most recent call last):
  File "/home/test.py", line 12, in <module>
    df = get_historical_data("GE", start=start, end=end, output_format="pandas", token="my_token")
  File "/home/venv/lib/python3.7/site-packages/iexfinance/stocks/__init__.py", line 44, in get_historical_data
    close_only=close_only, **kwargs).fetch()
  File "/home/venv/lib/python3.7/site-packages/iexfinance/base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "/home/venv/lib/python3.7/site-packages/iexfinance/base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "/home/venv/lib/python3.7/site-packages/iexfinance/base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.

Edit: I am close to using up my monthly message allocation (98%) at IEXCloud, could this be the reason I'm getting the error?

**Comment by addisonlynch** [comment]
Yes that is likely the error. We are working on repairing error reporting. Let me know if this continues to be an issue.
