### ISSUE TITLE
Yet another IEXQueryError when trying to get_social_sentiment?

### ISSUE THREAD

**Issue by windowshopr** [addisonlynch/iexfinance#192]
## Summary (include Python version)
Python 3.6, latest version of iexfinance as of Dec 21, 2019, Windows 10.

Receiving full error:
```
C:\Users\...\iexfinance\altdata\__init__.py:48: UserWarning: UNSTABLE ENDPOINT: Not yet fully implemented by the provider.
  warnings.warn("UNSTABLE ENDPOINT: Not yet fully implemented by the "
Traceback (most recent call last):
  File "test.py", line 266, in <module>
    print(get_social_sentiment("AAPL"))
  File "C:\Users\...\iexfinance\altdata\__init__.py", line 50, in get_social_sentiment
    return SocialSentiment(symbol, period_type, date, **kwargs).fetch()
  File "C:\...\iexfinance\altdata\base.py", line 50, in fetch
    return super(SocialSentiment, self).fetch()
  File "C:\...\iexfinance\base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "C:\...\iexfinance\base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "C:\...\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.
```

Any ideas? I'm using this as my code:

```
from iexfinance.altdata import get_social_sentiment
import os

os.environ['IEX_TOKEN'] = 'MY_API_TOKEN_IS_HERE'
print(get_social_sentiment("AAPL"))
```

Any ideas? I know this returns "unstable" results, but would expect AAPL to be a pretty reliable one to test with. I also only have the free tier account API. Would that be the issue? I'm nowhere near my monthly limit for requests.

### Date/time of issue
Dec 21, 2019 - 11:58 PM

### Expected behavior
To get the social sentiment data.

### Actual behavior
See above. Thanks!

**Comment by addisonlynch** [comment]
This data is not available in the free tier.
