### ISSUE TITLE
Chart endpoint not correctly downloading

### ISSUE THREAD

**Issue by addisonlynch** [addisonlynch/iexfinance#2]
**Default options**

```python
aapl = iex("AAPL")
aapl.get_chart()
```
Returns

> []

**Non-default options**

```python
aapl2 = iex("AAPL", chartRange='1d')
```
Returns 

>Traceback (most recent call last):
  File "test.py", line 3, in <module>
    aapl = iex("AAPL", chartRange='1d')
  File "/home/addison/Documents/iex/iexenv/lib/python3.5/site-packages/iexfinance/__init__.py", line 14, in IexFinance
    inst = Share(symbol, **kwargs)
  File "/home/addison/Documents/iex/iexenv/lib/python3.5/site-packages/iexfinance/__init__.py", line 39, in __init__
    self.data_set = self.refresh()        
  File "/home/addison/Documents/iex/iexenv/lib/python3.5/site-packages/iexfinance/__init__.py", line 43, in refresh
    data = super(Share, self)._fetch()
  File "/home/addison/Documents/iex/iexenv/lib/python3.5/site-packages/iexfinance/iexretriever.py", line 215, in _fetch
    raise ValueError("Not all endpoints downloaded")
ValueError: Not all endpoints downloaded

**Comment by addisonlynch** [comment]
Thanks to Alessandro Visintin for pointing out this issue

**Comment by addisonlynch** [comment]
Seems that there is an issue with the IEX API, where it does not download the chart endpoint in batch requests when chart is specified following other endpoints. See iexg/IEX-API#156  for further info (awaiting response from IEX at the moment)
