### ISSUE TITLE
KeyError:'date' bug in "get_historical_data" - request is successful (and charged), but conversion to df errors

### ISSUE THREAD

**Issue by lgreen4** [addisonlynch/iexfinance#223]
Python version 3.8
You have a pretty serious bug in the API.  Note, sometimes this seems to work and sometimes it doesn’t.  Meaning I have successfully received a dataframe back.  My guess is certain symbols cause the fail becasue a random selection works for some random symbols, and not for others.  Note also, and MORE importantly, even on FAIL, my message usage increases, meaning I am charged for the call, but I do not successfully get the data back… 

### Expected behavior
Expected to receive a dataframe back with the data

### Actual behavior
When I call:
```
df=get_historical_data(symbols, start, end, output_format='pandas',
                    token=apitoken)
```
where symbols is a list of 5 random symbols that I pull from:
    `allsymbols=get_symbols(output_format='pandas',token=apitoken)
`
the following symbols are the random symbols that produced this error:
`symbols=['EPV', 'LIVKU', 'QUAL', 'MT', 'IYW']`

I get the following error:

```
df=get_historical_data(symbols, start, end, output_format='pandas',
                token=apitoken)
```
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2646, in get_loc
    return self._engine.get_loc(key)

  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-104-bd2000ccf1a0>", line 1, in <module>
    df=get_historical_data(symbols, start, end, output_format='pandas',

  File "C:\ProgramData\Anaconda3\lib\site-packages\iexfinance\stocks\__init__.py", line 43, in get_historical_data
    return HistoricalReader(symbols, start=start, end=end,

  File "C:\ProgramData\Anaconda3\lib\site-packages\iexfinance\base.py", line 210, in fetch
    return self._output_format(data, fmt_j=fmt_j, fmt_p=fmt_p)

  File "C:\ProgramData\Anaconda3\lib\site-packages\iexfinance\stocks\historical.py", line 68, in _output_format
    df["date"] = pd.DatetimeIndex(df["date"])

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))

  File "pandas\_libs\index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc

  File "pandas\_libs\hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item

  File "pandas\_libs\hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item

KeyError: 'date'

**Comment by lgreen4** [comment]
Looks like the symbol 'LIVKU' is the culprit (or an example of other culprits) out of the sample "symbols" list, as it returns 
`df`
```
Out[124]: 
      LIVKU
chart    []
```

**Comment by lgreen4** [comment]
I think you just need to put a check in the historical.py, when you create the result dict, the data needs to conform to the correct format.  an empty dict looks like the problem...

**Comment by addisonlynch** [comment]
Looks like there is an error with the formatting function. This will be repaired in 0.5.0 (~1 week). Thanks.
