### ISSUE TITLE
Error: TimeoutError

### ISSUE THREAD

**Issue by aceidon** [addisonlynch/iexfinance#36]
I keep getting a TimeoutError for everything I try.  Not entirely sure what I'm doing wrong here.  The code for this has worked sporadically before but it all seems very intermittent.

```
from iexfinance import Stock
s = Stock("AAPL")
print(s.get_book())
```
Here are the error details:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "C:\Python3\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "C:\Python3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Python3\lib\site-packages\urllib3\connection.py", line 284, in connect
    conn = self._new_conn()
  File "C:\Python3\lib\site-packages\urllib3\connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x070F8AD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Python3\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python3\lib\site-packages\urllib3\util\retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.iextrading.com', port=443): Max retries exceeded with url: /1.0/stock/market/batch?symbols=AAPL&types=book (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x070F8AD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/PycharmProjects/run_main.py", line 90, in <module>
    print(s.get_book())
  File "C:\Python3\lib\site-packages\iexfinance\stock.py", line 32, in _format_wrapper
    response = func(self, *args, **kwargs)
  File "C:\Python3\lib\site-packages\iexfinance\stock.py", line 270, in get_book
    data = self._get_endpoint("book", kwargs)
  File "C:\Python3\lib\site-packages\iexfinance\stock.py", line 205, in _get_endpoint
    data = self.fetch()
  File "C:\Python3\lib\site-packages\iexfinance\base.py", line 141, in fetch
    return self._execute_iex_query(url)
  File "C:\Python3\lib\site-packages\iexfinance\base.py", line 111, in _execute_iex_query
    response = self.session.get(url=url)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python3\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python3\lib\site-packages\requests\adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.iextrading.com', port=443): Max retries exceeded with url: /1.0/stock/market/batch?symbols=AAPL&types=book (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x070F8AD0>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))

Process finished with exit code 1

**Comment by addisonlynch** [comment]
Are you using an HTTP proxy? Sometimes that can cause issues.
