### ISSUE TITLE
Get Financials Endpoint Does Not Handle Blank Values

### ISSUE THREAD

**Issue by exiao** [addisonlynch/iexfinance#63]
## Summary (include Python version)
>>> a = Stock('AADR')
>>> a.get_financials()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/ericxiao/.local/share/virtualenvs/bloom-Eg4XHhZg/lib/python3.6/site-packages/iexfinance/stock.py", line 32, in _format_wrapper
    response = func(self, *args, **kwargs)
  File "/Users/ericxiao/.local/share/virtualenvs/bloom-Eg4XHhZg/lib/python3.6/site-packages/iexfinance/stock.py", line 391, in get_financials
    for symbol in list(data)}
  File "/Users/ericxiao/.local/share/virtualenvs/bloom-Eg4XHhZg/lib/python3.6/site-packages/iexfinance/stock.py", line 391, in <dictcomp>
    for symbol in list(data)}
KeyError: 'financials'

### Expected behavior
It should handle empty state for finances more gracefully and return an empty dictionary

### Actual behavior
On bulk entry for get_financials(), it breaks and shows the KeyError exception

**Comment by reixd** [comment]
Hello @exiao,

this issue has been fixed with commit https://github.com/addisonlynch/iexfinance/commit/4912720b16a6cf8076576df78e9c55f977e12c6e on branch _Dev_.
You can checkout that branch or wait until a new release comes out

**Comment by addisonlynch** [comment]
@exiao the master branch has the same commits and should fix the problem as well. Install via ``pip install git+https://github.com/addisonlynch/iexfinance``. Will be pushed to Pypi in the next release.

**Comment by exiao** [comment]
Awesome, thank you :)
