### ISSUE TITLE
Stocks: 'Remote end closed connection without response'

### ISSUE THREAD

**Issue by ktrublu** [addisonlynch/iexfinance#91]
## Summary (include Python version)

'Remote end closed connection without response'

from iexfinance import Stock

symbols = pd.read_csv(file_string, header=0, names=['Ticker','Company','Sector','Industry','Country','Market Cap'] )

symbols = pd.DataFrame(symbols)

length = len(symbols)
i = 0

while i < length:  
    pullSymbol = symbols['Ticker'][i]
    quote = Stock(pullSymbol)
    OHLC = quote.get_ohlc()
    Open = quote.get_open()
    High = OHLC['high']
    Low = OHLC['low']
    Close = quote.get_close()
    Volume = quote.get_volume()
    i += 1

### Date/time of issue
Occurs randomly most times I run the above code. Sometimes after 50 loops, sometimes only after 3.

### Expected behavior
I would expect the connection not to close unexpectedly.
I am not using an HTTP proxy.

### Actual behavior
Traceback (most recent call last):
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\http\client.py", line 265, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ktru\OneDrive\Documents\HutchViz\RSI_Discipline\CollectStockData_from_IEX_and_Append.py", line 95, in <module>
    Close = quote.get_close()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stock.py", line 106, in _format_wrapper
    data = func(self, *args, **kwargs)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stock.py", line 621, in get_close
    return self.get_quote(filter_="close")
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stock.py", line 30, in _format_wrapper
    response = func(self, *args, **kwargs)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stock.py", line 538, in get_quote
    data = self._get_endpoint("quote", kwargs)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stock.py", line 203, in _get_endpoint
    data = self.fetch()
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 134, in fetch
    return self._execute_iex_query(url)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 106, in _execute_iex_query
    response = self.session.get(url=url, params=self.params)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ktru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
>>>

**Comment by ktrublu** [comment]
The connection drop seemed to be happening with get_open() and get_close().
So I stopped using those and replaced the above affected lines with:
    High = OHLC['high']
    Low = OHLC['low']

And now it all seems to be working fine.

**Comment by ktrublu** [comment]
typo above.
did not replace or change anything for high or low, only open and close with this:
    Open = OHLC['open']['price']
    Close = OHLC['close']['price']
